# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-18 01:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('demograp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q_country',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='What country are you from?'),
        ),
    ]
