# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('a_task_income', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('b_task_income', otree.db.models.CurrencyField(null=True)),
                ('treatment', otree.db.models.LongStringField(null=True)),
                ('value_type', otree.db.models.LongStringField(null=True)),
                ('elicitation_method', otree.db.models.LongStringField(null=True)),
                ('BDM_type', otree.db.models.LongStringField(null=True)),
                ('BDM_lolimit', otree.db.models.LongStringField(null=True)),
                ('BDM_uplimit', otree.db.models.LongStringField(null=True)),
                ('BDM_list_step', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('SOP_price', otree.db.models.CurrencyField(null=True)),
                ('take_rate', otree.db.models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('expected_take_rate', otree.db.models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('money_taken', otree.db.models.CurrencyField(null=True)),
                ('want_send_message', otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True)),
                ('b_message', otree.db.models.LongStringField(blank=True, default='', null=True)),
                ('b_value', otree.db.models.CurrencyField(blank=True, null=True)),
                ('message_price', otree.db.models.CurrencyField(null=True)),
                ('msg_sent', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0)),
                ('SOP_yes', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True)),
                ('price_list_size', otree.db.models.IntegerField(null=True)),
                ('time_ADecides', otree.db.models.LongStringField(null=True)),
                ('time_BPredicts', otree.db.models.LongStringField(null=True)),
                ('time_ATakeResults', otree.db.models.LongStringField(null=True)),
                ('time_AllFmNm', otree.db.models.LongStringField(null=True)),
                ('time_AllBdmCont', otree.db.models.LongStringField(null=True)),
                ('time_AllBdmList', otree.db.models.LongStringField(null=True)),
                ('time_AllSOP', otree.db.models.LongStringField(null=True)),
                ('time_BdmResults', otree.db.models.LongStringField(null=True)),
                ('time_DisplayMessageToA', otree.db.models.LongStringField(null=True)),
                ('time_DisplayMessagesToR', otree.db.models.LongStringField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_expression_group', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_expression_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('endowment', otree.db.models.CurrencyField(null=True)),
                ('participation_fee', otree.db.models.CurrencyField(null=True)),
                ('task_income', otree.db.models.CurrencyField(null=True)),
                ('available_income0', otree.db.models.CurrencyField(null=True)),
                ('available_income1', otree.db.models.CurrencyField(null=True)),
                ('time_InitialStage2', otree.db.models.LongStringField(null=True)),
                ('time_RolesIncome', otree.db.models.LongStringField(null=True)),
                ('time_Results', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PTT_expression.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_expression_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_expression_player', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_expression_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptt_expression_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_expression_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTT_expression.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTT_expression.Subsession'),
        ),
    ]
