# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-21 22:18
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_expression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ctrlQ_A_earnings',
            field=otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_A_earnings_err',
            field=otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_always_sends',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No'), ('It depends on his/her valuation for sending a message', 'It depends on his/her valuation for sending a message')], max_length=10000, null=True, verbose_name='Will the participant in Role B always send a message to the participant in Role A that he/she is matched with?'),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_always_sends_err',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No'), ('It depends on his/her valuation for sending a message', 'It depends on his/her valuation for sending a message')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_earnings',
            field=otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_earnings_err',
            field=otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_sends_message',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Will the message written by Role B be sent in this case?'),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_B_sends_message_err',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_anonymity',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Once you are paired with another participant, will you ever know the identity of this other participant?'),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_anonymity_err',
            field=otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_who_transfers',
            field=otree.db.models.StringField(choices=[('Role A', 'Role A'), ('Role B', 'Role B'), ('Role C', 'Role C'), ('Role R', 'Role R'), ('None of the above', 'None of the above')], max_length=10000, null=True, verbose_name='Who decides how much to take from Role B’s account and deposit it into Role A’s account?'),
        ),
        migrations.AddField(
            model_name='player',
            name='ctrlQ_who_transfers_err',
            field=otree.db.models.StringField(choices=[('Role A', 'Role A'), ('Role B', 'Role B'), ('Role C', 'Role C'), ('Role R', 'Role R'), ('None of the above', 'None of the above')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_ControlQuestions',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_Instructions',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
