# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 19:35
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_expression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='list_price_0_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_10_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_11_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_12_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_13_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_14_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_15_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_16_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_17_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_18_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_19_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_1_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_2_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_3_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_4_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_5_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_6_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_7_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_8_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_price_9_yes',
            field=otree.db.models.StringField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True),
        ),
    ]
