# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-22 22:56
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_expression', '0002_auto_20190521_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fields_checked',
            field=otree.db.models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='maxScreens',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_questions',
            field=otree.db.models.IntegerField(default=6, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pointDistMax',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pointDistMin',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='screenTime',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='target_income',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='task_reward',
            field=otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_GameInstructions',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_PracticeTask',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_SearchTask',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
