# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-30 22:09
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_expression', '0002_auto_20180830_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='list_compensation_0',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_1',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_10',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_11',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_12',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_13',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_14',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_15',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_16',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_17',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_18',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_19',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_2',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_3',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_4',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_5',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_6',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_7',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_8',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='list_compensation_9',
            field=otree.db.models.StringField(blank=True, choices=[('Send message', 'Send message'), ('Receive', 'Receive')], max_length=10000, null=True),
        ),
    ]
