# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-31 01:54
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_expression', '0003_auto_20180830_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='discard',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
