# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('treatment', otree.db.models.LongStringField(null=True)),
                ('value_type', otree.db.models.LongStringField(null=True)),
                ('elicitation_method', otree.db.models.LongStringField(null=True)),
                ('BDM_type', otree.db.models.LongStringField(null=True)),
                ('BDM_lolimit', otree.db.models.LongStringField(null=True)),
                ('BDM_uplimit', otree.db.models.LongStringField(null=True)),
                ('BDM_list_step', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_express_instructions_group', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_express_instructions_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('time_Instructions', otree.db.models.LongStringField(null=True)),
                ('time_ControlQuestions', otree.db.models.LongStringField(null=True)),
                ('endowment', otree.db.models.CurrencyField(null=True)),
                ('participation_fee', otree.db.models.CurrencyField(null=True)),
                ('number_of_questions', otree.db.models.IntegerField(default=6, null=True)),
                ('fields_checked', otree.db.models.IntegerField(default=-1, null=True)),
                ('ctrlQ_anonymity', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Once you are paired with another participant, will you ever know the identity of this other participant?')),
                ('ctrlQ_anonymity_err', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True)),
                ('ctrlQ_who_transfers', otree.db.models.StringField(choices=[('Role A', 'Role A'), ('Role B', 'Role B'), ('Role C', 'Role C'), ('Role R', 'Role R'), ('None of the above', 'None of the above')], max_length=10000, null=True, verbose_name='Who decides how much to take from Role B’s account and deposit it into Role A’s account?')),
                ('ctrlQ_who_transfers_err', otree.db.models.StringField(choices=[('Role A', 'Role A'), ('Role B', 'Role B'), ('Role C', 'Role C'), ('Role R', 'Role R'), ('None of the above', 'None of the above')], max_length=10000, null=True)),
                ('ctrlQ_B_always_sends', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No'), ('It depends on his/her valuation for sending a message', 'It depends on his/her valuation for sending a message')], max_length=10000, null=True, verbose_name='Will the participant in Role B always send a message to the participant in Role A that he/she is matched with?')),
                ('ctrlQ_B_always_sends_err', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No'), ('It depends on his/her valuation for sending a message', 'It depends on his/her valuation for sending a message')], max_length=10000, null=True)),
                ('ctrlQ_B_sends_message', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True, verbose_name='Will the message written by Role B be sent in this case?')),
                ('ctrlQ_B_sends_message_err', otree.db.models.StringField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10000, null=True)),
                ('ctrlQ_A_earnings', otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True)),
                ('ctrlQ_A_earnings_err', otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True)),
                ('ctrlQ_B_earnings', otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True)),
                ('ctrlQ_B_earnings_err', otree.db.models.StringField(choices=[('13.00 + X', '13.00 + X'), ('13.00 - X', '13.00 - X'), ('13.00 - X - Z', '13.00 - X - Z'), ('13.00 - X + Z', '13.00 - X + Z')], max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PTT_express_instructions.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_express_instructions_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptt_express_instructions_player', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_express_instructions_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptt_express_instructions_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'PTT_express_instructions_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTT_express_instructions.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTT_express_instructions.Subsession'),
        ),
    ]
